#!/usr/bin/env bun
/**
 * Patterson Design System — Starlight content generator
 * ------------------------------------------------------------------
 * Zero-dependency (Bun/Node built-ins only). Parses this repo's own
 * source of truth — tokens/*.css, theme.json, assets/icons/*, and each
 * component's .prompt.md contract — and writes Starlight markdown
 * pages into site/src/content/docs/{tokens,icons,components,specimens}.
 *
 * Re-runnable: every run wipes and rewrites its own output directories
 * only. The generated tree is gitignored — run this before `astro
 * build` (and `astro dev`), never commit its output. See
 * .github/workflows/pages.yml for the CI invocation.
 *
 * Run from the repo root: `bun run scripts/build-site-content.ts`
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SITE = path.join(ROOT, 'site');
const DOCS = path.join(SITE, 'src', 'content', 'docs');
const PUBLIC = path.join(SITE, 'public');

const GH_BLOB = 'https://github.com/patterson-agents/patterson-design-system/blob/main';
const GH_TREE = 'https://github.com/patterson-agents/patterson-design-system/tree/main';

// ---------------------------------------------------------------- utils

function readText(p: string): string {
  return readFileSync(p, 'utf8');
}

/**
 * Writes a generated page. `content` must start with the page's YAML
 * frontmatter (--- ... ---) — Astro requires frontmatter to open the file,
 * so the "generated" banner is spliced in right after it, not prepended.
 */
function writeGenerated(filePath: string, content: string) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  const banner =
    '<!-- GENERATED by scripts/build-site-content.ts — do not hand-edit. -->\n\n';
  const closeIndex = content.indexOf('\n---\n');
  if (closeIndex === -1) {
    throw new Error(`writeGenerated: ${filePath} content has no closing frontmatter fence`);
  }
  const splitAt = closeIndex + '\n---\n'.length;
  const withBanner = content.slice(0, splitAt) + '\n' + banner + content.slice(splitAt);
  writeFileSync(filePath, withBanner);
}

function resetDir(dir: string) {
  if (existsSync(dir)) rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
}

function frontmatter(fields: Record<string, string | number>): string {
  const lines = ['---'];
  for (const [k, v] of Object.entries(fields)) {
    if (typeof v === 'number') {
      lines.push(`${k}: ${v}`);
    } else {
      // YAML plain scalar is fine as long as we escape embedded quotes.
      const escaped = v.replace(/"/g, '\\"');
      lines.push(`${k}: "${escaped}"`);
    }
  }
  lines.push('---', '');
  return lines.join('\n');
}

function titleCaseFromSlug(slug: string): string {
  return slug
    .split(/[-_]/)
    .map((w) => (w.length ? w[0].toUpperCase() + w.slice(1) : w))
    .join(' ');
}

function isColorValue(value: string): boolean {
  return /^#([0-9a-f]{3,8})$/i.test(value.trim()) || /^(rgba?|hsla?)\(/i.test(value.trim());
}

// ------------------------------------------------------ tokens/*.css

type TokenEntry = { name: string; value: string; comment: string; section: string };

/** Extracts the (single) :root { ... } block's raw text, if any. */
function extractRootBlock(css: string): string | null {
  const m = css.match(/:root\s*\{([\s\S]*?)\n\}/);
  return m ? m[1] : null;
}

function parseTokens(rootBlock: string): TokenEntry[] {
  const entries: TokenEntry[] = [];
  let section = 'General';
  const lines = rootBlock.split('\n');
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    // A comment-only line, not attached to a property: treat as a section
    // label, e.g. `/* --- Navy tints ------------------------------- */`.
    const sectionMatch = line.match(/^\/\*\s*-*\s*(.+?)\s*-*\s*\*\/$/);
    if (sectionMatch && !line.includes(':')) {
      section = sectionMatch[1].replace(/^-+|-+$/g, '').trim() || section;
      continue;
    }
    // Bare multi-line comment continuation / prose — skip, not a token.
    if (line.startsWith('/*') || line.startsWith('*') || line.endsWith('*/')) {
      if (!line.includes('--')) continue;
    }

    const propMatch = line.match(/^(--[\w-]+)\s*:\s*([^;]+);\s*(\/\*(.*?)\*\/)?\s*$/);
    if (!propMatch) continue;
    const [, name, value, , rawComment] = propMatch;
    let comment = (rawComment || '').trim();
    comment = comment.replace(/@kind\s+\S+/g, '').trim();
    entries.push({ name, value: value.trim(), comment, section });
  }
  return entries;
}

type FontFace = { family: string; weight: string; style: string; src: string };

function parseFontFaces(css: string): FontFace[] {
  const faces: FontFace[] = [];
  const blocks = css.match(/@font-face\s*\{[^}]*\}/g) || [];
  for (const block of blocks) {
    const family = (block.match(/font-family:\s*'([^']+)'/) || [, ''])[1];
    const weight = (block.match(/font-weight:\s*([^;]+);/) || [, 'normal'])[1].trim();
    const style = (block.match(/font-style:\s*([^;]+);/) || [, 'normal'])[1].trim();
    const src = (block.match(/src:\s*([\s\S]*?);/) || [, ''])[1]
      .replace(/\s+/g, ' ')
      .trim();
    faces.push({ family, weight, style, src });
  }
  return faces;
}

function swatchCell(value: string): string {
  if (!isColorValue(value)) return `\`${value}\``;
  const safe = value.replace(/"/g, "'");
  return (
    `<span style="display:inline-flex;align-items:center;gap:6px">` +
    `<span style="width:14px;height:14px;border-radius:3px;border:1px solid var(--sl-color-hairline, #c9c9cc);background:${safe};display:inline-block"></span>` +
    `<code>${value}</code></span>`
  );
}

function tokenFileHeaderComment(css: string): string {
  const m = css.match(/\/\*([\s\S]*?)\*\//);
  if (!m) return '';
  return m[1]
    .split('\n')
    .map((l) => l.replace(/^\s*={0,}\s?/, '').trim())
    .filter((l) => l && !/^=+$/.test(l))
    .join(' ');
}

function buildTokensPages() {
  const tokensDir = path.join(ROOT, 'tokens');
  const outDir = path.join(DOCS, 'tokens');
  resetDir(outDir);

  const files = readdirSync(tokensDir)
    .filter((f) => f.endsWith('.css'))
    .sort();

  const perFileSummary: { slug: string; title: string; count: number }[] = [];

  for (const file of files) {
    const slug = file.replace(/\.css$/, '');
    const title = titleCaseFromSlug(slug);
    const css = readText(path.join(tokensDir, file));
    const rootBlock = extractRootBlock(css);
    const tokens = rootBlock ? parseTokens(rootBlock) : [];
    const fontFaces = parseFontFaces(css);
    const headerNote = tokenFileHeaderComment(css);

    let body = '';
    body += `Source: [\`tokens/${file}\`](${GH_BLOB}/tokens/${file}).\n\n`;
    if (headerNote) body += `${headerNote}\n\n`;

    if (tokens.length) {
      const bySection = new Map<string, TokenEntry[]>();
      for (const t of tokens) {
        if (!bySection.has(t.section)) bySection.set(t.section, []);
        bySection.get(t.section)!.push(t);
      }
      for (const [section, entries] of bySection) {
        body += `## ${section}\n\n`;
        body += `| Custom property | Value | Note |\n|---|---|---|\n`;
        for (const e of entries) {
          body += `| \`${e.name}\` | ${swatchCell(e.value)} | ${e.comment || ''} |\n`;
        }
        body += '\n';
      }
    }

    if (fontFaces.length) {
      body += `## @font-face declarations\n\n`;
      body += `| Family | Weight | Style | Source |\n|---|---|---|---|\n`;
      for (const f of fontFaces) {
        body += `| \`${f.family}\` | ${f.weight} | ${f.style} | \`${f.src}\` |\n`;
      }
      body += '\n';
    }

    if (!tokens.length && !fontFaces.length) {
      body += `This stylesheet declares no custom properties or \`@font-face\` rules of its ` +
        `own — it sets base element styles that *consume* tokens from the other files. ` +
        `See the full source below.\n\n`;
    }

    body += `<details>\n<summary>Full source — \`${file}\`</summary>\n\n`;
    body += '```css\n' + css.trimEnd() + '\n```\n\n</details>\n';

    // sidebar.order must be nested under `sidebar:`, not a dotted key —
    // build the flat frontmatter first, then splice the nested block in.
    const fm = frontmatter({
      title,
      description: `Generated reference for tokens/${file} — every custom property, its value, and a swatch where applicable.`,
    }).replace(/---\n$/, `sidebar:\n  order: ${files.indexOf(file) + 2}\n---\n`);

    writeGenerated(path.join(outDir, `${slug}.md`), fm + '\n' + body);
    perFileSummary.push({ slug, title, count: tokens.length + fontFaces.length });
  }

  buildTokensIndex(outDir, perFileSummary);
}

function buildTokensIndex(
  outDir: string,
  files: { slug: string; title: string; count: number }[],
) {
  const themePath = path.join(ROOT, 'theme.json');
  const theme = JSON.parse(readText(themePath));
  const meta = theme.$meta || {};

  let body = '';
  body += `Generated from [\`theme.json\`](${GH_BLOB}/theme.json), the machine-readable ` +
    `source every framework adapter under [\`integrations/\`](${GH_TREE}/integrations) is ` +
    `built from, and from each stylesheet in [\`tokens/\`](${GH_TREE}/tokens).\n\n`;

  body += `## Theme metadata\n\n| Field | Value |\n|---|---|\n`;
  for (const [k, v] of Object.entries(meta)) {
    if (typeof v === 'object') continue;
    body += `| \`${k}\` | ${String(v).replace(/\|/g, '\\|')} |\n`;
  }
  body += '\n';

  body += `## theme.json sections\n\n`;
  body += `| Section | Kind | Entries |\n|---|---|---|\n`;
  for (const [key, value] of Object.entries(theme)) {
    if (key.startsWith('$')) continue;
    const count =
      value && typeof value === 'object' ? Object.keys(value as object).length : 1;
    const kind = Array.isArray(value) ? 'array' : typeof value;
    body += `| \`${key}\` | ${kind} | ${count} |\n`;
  }
  body += '\n';

  body += `## Stylesheets\n\n`;
  body += `| File | Custom properties parsed | Reference |\n|---|---|---|\n`;
  for (const f of files) {
    body += `| \`tokens/${f.slug}.css\` | ${f.count} | [${f.title}](/tokens/${f.slug}/) |\n`;
  }
  body += '\n';

  body += `Edit \`tokens/*.css\` and \`theme.json\` together so they never drift — this page ` +
    `and the per-file pages regenerate from both on every build.\n`;

  const fm = frontmatter({
    title: 'Tokens',
    description: 'Summary of theme.json and every stylesheet in tokens/, generated on every build.',
  }).replace(/---\n$/, 'sidebar:\n  order: 1\n---\n');

  writeGenerated(path.join(outDir, 'index.md'), fm + '\n' + body);
}

// ------------------------------------------------------------- icons

function buildIconsPage() {
  const manifestPath = path.join(ROOT, 'assets', 'icons', 'icons-manifest.json');
  const manifest: { glyph: string; file: string; unicode: string; advX: number }[] =
    JSON.parse(readText(manifestPath));

  // Copy the SVGs into the Astro public dir so they resolve during a
  // standalone `astro build`/`astro dev` as well as in the composed,
  // multi-directory Pages artifact (where /assets/icons/ is also a
  // top-level passthrough copy of the same source files).
  const iconsSrcDir = path.join(ROOT, 'assets', 'icons');
  const iconsOutDir = path.join(PUBLIC, 'assets', 'icons');
  resetDir(iconsOutDir);
  for (const entry of manifest) {
    const src = path.join(iconsSrcDir, entry.file);
    if (existsSync(src)) {
      writeFileSync(path.join(iconsOutDir, entry.file), readFileSync(src));
    }
  }

  let body = '';
  body += `${manifest.length} glyphs from the official \`patterson-icons\` webfont, extracted ` +
    `as standalone SVGs — one per glyph, generated from ` +
    `[\`assets/icons/icons-manifest.json\`](${GH_BLOB}/assets/icons/icons-manifest.json). See ` +
    `[Shapes → Iconography](/design/shapes/) for usage rules, and the ` +
    `[icons token page](/tokens/icons/) for the \`patterson-icons\` \`@font-face\` and the ` +
    `\`.pat-i-*\` class map.\n\n`;

  body += `| Glyph | Preview | Unicode | File |\n|---|---|---|---|\n`;
  for (const entry of manifest) {
    body += `| \`${entry.glyph}\` | <img src="/assets/icons/${entry.file}" alt="${entry.glyph} icon" width="20" height="20" /> | \`${entry.unicode}\` | \`${entry.file}\` |\n`;
  }
  body += '\n';

  const fm = frontmatter({
    title: 'Icon library',
    description: `Every glyph in the official patterson-icons font (${manifest.length} icons), rendered inline and generated on every build.`,
  });

  writeGenerated(path.join(DOCS, 'icons.md'), fm + '\n' + body);
}

// -------------------------------------------------------- components

type ComponentDef = { category: string; name: string; slug: string };

function findComponents(): ComponentDef[] {
  const componentsDir = path.join(ROOT, 'components');
  const categories = readdirSync(componentsDir).filter((f) =>
    statSync(path.join(componentsDir, f)).isDirectory(),
  );
  const defs: ComponentDef[] = [];
  for (const category of categories) {
    const dir = path.join(componentsDir, category);
    const jsxFiles = readdirSync(dir).filter((f) => f.endsWith('.jsx'));
    for (const jsxFile of jsxFiles) {
      const name = jsxFile.replace(/\.jsx$/, '');
      defs.push({ category, name, slug: name.toLowerCase() });
    }
  }
  return defs.sort((a, b) => a.name.localeCompare(b.name));
}

/** Synthesizes a contract for a component with no .prompt.md (currently: Icon). */
function synthesizeContract(category: string, name: string): string {
  const dtsPath = path.join(ROOT, 'components', category, `${name}.d.ts`);
  const jsxPath = path.join(ROOT, 'components', category, `${name}.jsx`);
  const dts = existsSync(dtsPath) ? readText(dtsPath) : '';
  const jsx = existsSync(jsxPath) ? readText(jsxPath) : '';

  const topDoc = jsx.match(/\/\*\*([\s\S]*?)\*\//);
  const prose = topDoc
    ? topDoc[1]
        .split('\n')
        .map((l) => l.replace(/^\s*\*\s?/, ''))
        .filter((l) => !l.trim().startsWith('<'))
        .join('\n')
        .trim()
    : `The \`${name}\` component. No \`.prompt.md\` contract exists for this component in ` +
      `the source tree — this page is synthesized from its \`.d.ts\` and \`.jsx\` source.`;

  const usageLines = jsx
    .split('\n')
    .filter((l) => l.trim().startsWith('<' + name));

  let body = `${prose}\n\n`;
  if (usageLines.length) {
    body += '```jsx\n' + usageLines.map((l) => l.trim().replace(/^\*\s?/, '')).join('\n') + '\n```\n\n';
  }

  const propsMatch = dts.match(/interface \w+Props[^{]*\{([\s\S]*?)\n\}/);
  if (propsMatch) {
    body += `Props:\n\n| Prop | Type | Description |\n|---|---|---|\n`;
    const propLines = propsMatch[1].split('\n');
    let pendingComment = '';
    for (const line of propLines) {
      const t = line.trim();
      if (t.startsWith('/**')) {
        pendingComment = t.replace(/^\/\*\*\s?/, '').replace(/\*\/\s*$/, '').trim();
        continue;
      }
      const propMatch = t.match(/^(\w+)(\??):\s*([^;]+);?/);
      if (propMatch) {
        const [, propName, optional, type] = propMatch;
        const escType = type.trim().replace(/\|/g, '\\|');
        const escComment = pendingComment.replace(/\|/g, '\\|');
        body += `| \`${propName}${optional}\` | \`${escType}\` | ${escComment} |\n`;
        pendingComment = '';
      }
    }
    body += '\n';
  }

  return body;
}

function buildComponentPages() {
  const outDir = path.join(DOCS, 'components');
  resetDir(outDir);
  const defs = findComponents();

  let indexBody = '';
  indexBody += `${defs.length} components across core, feedback, and forms, documented from ` +
    `each component's own \`.prompt.md\` contract in [\`components/\`](${GH_TREE}/components) ` +
    `(synthesized from its \`.d.ts\`/\`.jsx\` source where no \`.prompt.md\` exists — see ` +
    `[Icon](/components/icon/)). Every component ships a \`.jsx\` implementation and a ` +
    `\`.d.ts\` type contract; all are available as React primitives on ` +
    `\`window.PattersonCompaniesDesignSystem_3534f9\`.\n\n`;
  indexBody += `See them all live, in every variant and state, in the ` +
    `[kitchen sink](/site/kitchen-sink.html).\n\n`;
  indexBody += `| Component | Category |\n|---|---|\n`;

  for (const def of defs) {
    const promptPath = path.join(ROOT, 'components', def.category, `${def.name}.prompt.md`);
    const hasPrompt = existsSync(promptPath);
    const contractBody = hasPrompt ? readText(promptPath).trim() + '\n' : synthesizeContract(def.category, def.name);

    const jsxHref = `${GH_BLOB}/components/${def.category}/${def.name}.jsx`;
    const dtsHref = `${GH_BLOB}/components/${def.category}/${def.name}.d.ts`;
    // kitchen-sink.jsx's own <Sec id> values match the lowercased component
    // name, with one exception: Button's section is id="buttons" (plural).
    const kitchenSinkAnchor = def.slug === 'button' ? 'buttons' : def.slug;

    let body = contractBody;
    body += `\n---\n\nSource: [\`${def.name}.jsx\`](${jsxHref}) · [\`${def.name}.d.ts\`](${dtsHref}) ` +
      `· category: \`${def.category}\` · live: [kitchen sink](/site/kitchen-sink.html#${kitchenSinkAnchor})\n`;

    const fm = frontmatter({
      title: def.name,
      description: `Component contract for ${def.name} (${def.category}).`,
    });
    writeGenerated(path.join(outDir, `${def.slug}.md`), fm + '\n' + body);

    indexBody += `| [${def.name}](/components/${def.slug}/) | ${def.category} |\n`;
  }

  const fm = frontmatter({
    title: 'Components',
    description: 'Every Patterson component, documented from its .prompt.md contract, generated on every build.',
  }).replace(/---\n$/, 'sidebar:\n  order: 1\n---\n');
  writeGenerated(path.join(outDir, 'index.md'), fm + '\n' + indexBody);
}

// -------------------------------------------------------- specimens

function humanizeCardName(file: string): string {
  const slug = file.replace(/\.card\.html$/, '');
  return titleCaseFromSlug(slug);
}

function buildSpecimenPages() {
  const outDir = path.join(DOCS, 'specimens');
  resetDir(outDir);

  // -- Guideline reference cards --------------------------------------
  const guidelinesDir = path.join(ROOT, 'guidelines');
  const cards = readdirSync(guidelinesDir)
    .filter((f) => f.endsWith('.card.html'))
    .sort();

  let guidelinesBody = '';
  guidelinesBody += `${cards.length} brand guideline reference cards from ` +
    `[\`guidelines/\`](${GH_TREE}/guidelines), served as passthrough static HTML — each ` +
    `link opens the live card, not a copy.\n\n`;
  guidelinesBody += `| Card | Link |\n|---|---|\n`;
  for (const file of cards) {
    guidelinesBody += `| ${humanizeCardName(file)} | [\`${file}\`](/guidelines/${file}) |\n`;
  }
  guidelinesBody += '\n';

  writeGenerated(
    path.join(outDir, 'guidelines.md'),
    frontmatter({
      title: 'Guideline cards',
      description: `Every brand guideline reference card in guidelines/ (${cards.length} cards), linked live and generated on every build.`,
    }).replace(/---\n$/, 'sidebar:\n  order: 1\n---\n') +
      '\n' +
      guidelinesBody,
  );

  // -- Template demos ---------------------------------------------------
  const templatesDir = path.join(ROOT, 'templates');
  const templateDirs = readdirSync(templatesDir)
    .filter((f) => statSync(path.join(templatesDir, f)).isDirectory())
    .sort();

  let templatesBody = '';
  templatesBody += `${templateDirs.length} page/deck/site scaffolds from ` +
    `[\`templates/\`](${GH_TREE}/templates), served as passthrough static HTML — each link ` +
    `opens the live demo.\n\n`;
  templatesBody += `| Template | Entry point |\n|---|---|\n`;
  for (const dir of templateDirs) {
    const dirPath = path.join(templatesDir, dir);
    const htmlFiles = readdirSync(dirPath).filter((f) => f.endsWith('.html'));
    const entry =
      htmlFiles.find((f) => f.toLowerCase() === 'index.html') || htmlFiles[0];
    const label = titleCaseFromSlug(dir);
    templatesBody += entry
      ? `| ${label} | [\`templates/${dir}/${entry}\`](/templates/${dir}/${entry}) |\n`
      : `| ${label} | *(no HTML entry point found)* |\n`;
  }
  templatesBody += '\n';

  writeGenerated(
    path.join(outDir, 'templates.md'),
    frontmatter({
      title: 'Template demos',
      description: `Every page/deck/site template in templates/ (${templateDirs.length} templates), linked live and generated on every build.`,
    }).replace(/---\n$/, 'sidebar:\n  order: 2\n---\n') +
      '\n' +
      templatesBody,
  );

  // -- Landing page ------------------------------------------------------
  let indexBody = '';
  indexBody += `Passthrough specimens — plain static HTML, served live and unmodified, not ` +
    `copied into this site's build. Two collections:\n\n`;
  indexBody += `- **[Guideline cards](/specimens/guidelines/)** — ${cards.length} brand ` +
    `reference cards from [\`guidelines/\`](${GH_TREE}/guidelines): logo, icons, palette, ` +
    `type, interaction states, and more.\n`;
  indexBody += `- **[Template demos](/specimens/templates/)** — ${templateDirs.length} page, ` +
    `deck, and site scaffolds from [\`templates/\`](${GH_TREE}/templates).\n`;

  writeGenerated(
    path.join(outDir, 'index.md'),
    frontmatter({
      title: 'Specimens',
      description: 'Guideline cards and template demos, served live as passthrough static HTML.',
    }).replace(/---\n$/, 'sidebar:\n  order: 0\n---\n') +
      '\n' +
      indexBody,
  );
}

// -------------------------------------------------------------- main

function main() {
  console.log('Patterson Design System — generating Starlight content…');
  buildTokensPages();
  console.log('  tokens/       done');
  buildIconsPage();
  console.log('  icons.md      done');
  buildComponentPages();
  console.log('  components/   done');
  buildSpecimenPages();
  console.log('  specimens/    done');
  console.log('Done.');
}

main();
